version: 0.1.{build}

image: Visual Studio 2019

configuration: Release

build_script:
- cmd: dotnet build -c Release src/Hangfire.Mongo/Hangfire.Mongo.csproj

artifacts:
- path: src/Hangfire.Mongo/bin/Release/Hangfire.Mongo.*.nupkg

deploy:
  provider: NuGet
  api_key: 
    secure: r99ajvg5sdr11376858hcnxa
  skip_symbols: false
  artifact: /.*\.nupkg/
  
  on:
    branch: master
